### ISSUE TITLE
[DTVD] On latest build, All VDs are reset to 12000m (MAX VD) every time open the VD menu.

### ISSUE THREAD

**Issue by Apricot-ale** [DomT602/Doms-Arma-3-Mods#12]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14 STABLE` STEAM Latest Version
- **CBA:** `3.16.1 STABLE` STEAM Latest Version
- **ACE:** `3.16.3 STABLE` STEAM Latest Version

**Description:**
When using DTVD Latest build (with using file in github), All VD settings are reset to 12000m every time when Opening VD Menu.

**Steps to reproduce:**
- Build/Packing DTVD Folder to PBO with Arma 3 Tools Addon Builder without Binarize.
- Make addon folder `@DTVD\Addons\DTVD.pbo`.
- Open Arma3 Launcher and add CBA_A3 and ace to load order (both steam STABLE).
- D&D to @DTVD folder to A3 Launcher then adds to load order.
- Launch game
- Open ACE Arsenal (or some singlemissions)
- Open VD Menu (Already reset to 12000m)
- Set foot (or any) VD to 200m (I try type/slider both, but never care)
- VD looks ok. but Close and Reopen VD Menu...
- VD are reset to 12000m.

**Expected behavior:**
Those should be hold last setting (200m). but not saved (12000m).

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Virtual Arsenal (ACE)

**Log Files:**
- [Arma3_x64_2024-03-25_09-11-29.rpt.txt](https://github.com/DomT602/Doms-Arma-3-Mods/files/14737325/Arma3_x64_2024-03-25_09-11-29.rpt.txt)

**Additional context:**
I use this file. latest main branch, build with Arma3 Addon Builder.
[addons.zip](https://github.com/DomT602/Doms-Arma-3-Mods/files/14737341/addons.zip)
Used profile is not new profile. 
Using daily basis profile with Steam version of DTVD. and this did not occur with the Steam version.

**Comment by DomT602** [comment]
Thanks for the detailed report, I've found the source of the bug (being the default values in the menu) and fixed it in here: https://github.com/DomT602/Doms-Arma-3-Mods/commit/21feb83d3776d30ea1e7a35188f0f85562b574f0
I'll try and get the steam version updated later today.
